# 建议全部显式指明，这样实际配置能全部记录
# this must be provided
#run_name: 'default'
#run_description: "default description"

# here is data, model and metric, it depends on the project
# y_rgb have no effect on these
# ==============================
your_dataset:

model:
  type: NumericDecoder
  your_arg1: 1
  your_arg2: 2
metric:
  # 自定义metric可以按照model保存在这

# ==============================
#optimizer:
  # 使用的是AdamW
#  lr: 3e-4
#  weight_decay: 0.01
scheduler:
  type: "LinearWarmupCosineLRScheduler"
  min_lr: 3e-5
  max_lr: 3e-4
  warmup_rate: 0.1
  warmup_start_lr: 1e-5
training:
  # 必须指定
  epochs: 10
#  is_sweep: false
#  ds_config: null
#  gradient_accumulation: 1
#  resume_from: null
#  activation_checkpoint: null
#  grad_clip: null
#  fp16: false

#  print_model: true
  # false means loss is <not> [greater is better].
#  progress_show:
#    loss: false
#  valid_every_n_epochs: 1
#  test_every_n_epochs: 1
#  progress_every_n_epochs: 1
#  progress_every_n_batches: 1

# below list all the config of runner with the default value
# you can change it if you want
#log:
#  to_file: true
#  folder: "./logs"
#  log_level: "INFO"
#pt:
#  pt_save: true
#  pt_save_dir: "./checkpoints"
#  # 不互斥，若同时指定n_epochs, n_batches, 则都会生效
#  pt_best_monitor:
#    loss: false
#  pt_topk: 3
#  pt_save_n_epochs: 1
#  pt_save_n_batches: null
#wandb:
#  wandb_enable: false
#  wandb_project_name: "default"
#  wandb_offline: false
#  wandb_dir: "./"
#  wandb_tags: null
